version: "3"

services:
  db:
    image: "mongo"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "argentBankDB"
    volumes:
      - "./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
      - "argentBankDB:/data/db"

  db-ui:
    image: "mongo-express"
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - "db"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "root"
      ME_CONFIG_MONGODB_URL: "mongodb://root:root@db:27017/"
      ME_CONFIG_BASICAUTH: "false"

  api:
    build:
      context: .
      dockerfile: "docker/api.dockerfile"
    image: "oc-argentbank-api"
    restart: "always"
    ports:
      - "3001:3001"
    depends_on:
      - "db"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command: "npm run server"
    environment:
      DATABASE_URL: "mongodb://app:password@db:27017/argentBankDB"
      PORT: "3001"

  web:
    build:
      context: .
      dockerfile: "docker/web.dockerfile"
    image: "oc-argentbank-web"
    restart: "always"
    ports:
      - "3000:3000"
    volumes:
      - "./:/app:rw"
      - "node_modules:/app/node_modules:rw"
    command: "bun run dev --host 0.0.0.0 --debug true"
    environment:
      VITE_API_URL: "http://localhost:3001"

  populate-db:
    image: "node"
    restart: "no"
    depends_on:
      - "api"
    command:
      - /bin/bash
      - -c
      - |
        echo "Installing dependencies..."
        mkdir -p /scripts
        cd /scripts
        npm init -y
        npm install axios
        
        echo "Downloading populate db script..."
        curl -o script.js https://raw.githubusercontent.com/wilson-kbs/oc-13-api/master/server/scripts/populateDatabase.js
        sed -i "s/localhost:3001/api:3001/g" script.js
        
        echo "Running script..."
        node script.js


volumes:
  argentBankDB:
  node_modules:
